# Generated by Django 2.2.8 on 2020-08-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0006_auto_20200819_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='project',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='project',
            name='upvote',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
