# Generated by Django 2.2.8 on 2020-08-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0007_auto_20200819_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='downvote',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='upvote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
